export default {
    index: { title: 'Overview' },
    gpt4o: { title: 'GPT-4o' },
    gpt4o_mini: { title: 'GPT-4o mini' },
    o1: { title: 'o1 / o1-preview' },
    sora: { title: 'Sora' },
    gemini_1_5: { title: 'Gemini 1.5' },
    claude3: { title: 'Claude 3' },
    llama3_1: { title: 'Llama 3.1' },
    deepseek_v2: { title: 'DeepSeek-V2' },
    deepseek_v3: { title: 'DeepSeek-V3' },
    deepseek_r1: { title: 'DeepSeek-R1' },
    mistral_large_2: { title: 'Mistral Large 2' },
    hunyuan_large: { title: 'Hunyuan-Large' },
    qwen25: { title: 'Qwen2.5 / Qwen2.5-VL' },
    glm4: { title: 'GLM-4 / GLM-4V' },
    kimi: { title: 'Kimi / Kimi+' },
    minimax: { title: 'MiniMax / Abab' },
    step: { title: 'Step-1 / Step-2' },
}
