export default {
    index: { title: 'Overview' },
    gpt4: { title: 'GPT-4' },
    gpt4v: { title: 'GPT-4V' },
    claude2: { title: 'Claude 2' },
    claude3: { title: 'Claude 3 Family' },
    llama1: { title: 'Llama 1' },
    llama2: { title: 'Llama 2' },
    llama3: { title: 'Llama 3' },
    mistral7b: { title: 'Mistral 7B' },
    mixtral_8x7b: { title: 'Mixtral 8x7B' },
    qwen2: { title: 'Qwen1.5 / Qwen2' },
    deepseek_v2: { title: 'DeepSeek-V2' },
    gemini_1: { title: 'Gemini 1.0 / 1.5' },
    stable_diffusion_23: { title: 'Stable Diffusion 2 / 3' },
    midjourney: { title: 'Midjourney v5 / v6' },
    ernie4: { title: 'ERNIE 4.0' },
    yi_34b: { title: 'Yi-34B' },
}
