export default {
  index: { title: '概览' },
  rust: { title: 'Rust' },
  kotlin: { title: 'Kotlin' },
  elixir: { title: 'Elixir' },
  dart: { title: 'Dart' },
  typescript: { title: 'TypeScript' },
  julia: { title: 'Julia' },
  elm: { title: 'Elm' },
  purescript: { title: 'PureScript' },
  hack: { title: 'Hack' },
  swift: { title: 'Swift' },
  crystal: { title: 'Crystal' },
  solidity: { title: 'Solidity' },
}
