export default {
    'index': { title: 'Index' },
    'tencent': { title: 'Tencent' },
    'alibaba': { title: 'Alibaba' },
    'bytedance': { title: 'ByteDance' },
    'baidu': { title: 'Baidu' },
    'jd': { title: 'JD.com' },
    'pinduoduo': { title: 'Pinduoduo' },
    'meituan': { title: 'Meituan' },
    'netease': { title: 'NetEase' },
    'bilibili': { title: 'Bilibili' },
    'xiaohongshu': { title: 'Xiaohongshu (RED)' },
    'kuaishou': { title: 'Kuaishou' },
    'ctrip': { title: 'Trip.com Group (Ctrip)' },
    'huawei': { title: 'Huawei' },
    'xiaomi': { title: 'Xiaomi' },
    'lenovo': { title: 'Lenovo' },
    'zte': { title: 'ZTE' },
    'dji': { title: 'DJI' },
    'byd': { title: 'BYD' },
    'li-auto': { title: 'Li Auto' },
    'nio': { title: 'NIO' },
    'xpeng': { title: 'XPeng' },
    'seres': { title: 'Seres (AITO)' },
    'deepseek': { title: 'DeepSeek' },
    'ant-group': { title: 'Ant Group' },
    'jd-tech': { title: 'JD Technology' },
    'sensetime': { title: 'SenseTime' },
}
