export default {
    index: {
        title: 'Introduction',
        type: 'page',
        display: 'hidden',
        theme: { layout: 'full', toc: false, timestamp: false },
    },
    '---sep-time': { type: 'separator', title: 'Timeline & languages' },
    'ai-timeline': { title: 'AI Timeline', type: 'page' },
    timeline: { title: 'Programming Languages', type: 'page' },
    '---sep-ai': { type: 'separator', title: 'Models · software · data' },
    ais: { title: 'AI Models', type: 'page' },
    software: { title: 'AI Software', type: 'page' },
    datasets: { title: 'AI Datasets', type: 'page' },
    '---sep-noaics': { type: 'separator', title: 'Core CS (beyond AI-only)' },
    noaics: { title: 'NOAICS', type: 'page' },
    '---sep-hw': { type: 'separator', title: 'Hardware & AGI' },
    hardware: { title: 'Hardware', type: 'page' },
    agi: { title: 'AGI', type: 'page' },
    '---sep-web3': { type: 'separator', title: 'Web3 & Decentralization' },
    web3: { title: 'Web3', type: 'page' },
    '---sep-more': { type: 'separator', title: 'Industry & reference' },
    companies: { title: 'Tech Giants', type: 'page' },
    appendix: { title: 'Appendix', type: 'page' },
}
