export default {
  index: { title: '概览' },
  ada: { title: 'Ada' },
  'c++': { title: 'C++' },
  'objective-c': { title: 'Objective-C' },
  abap: { title: 'ABAP' },
  vhdl: { title: 'VHDL' },
  'common-lisp': { title: 'Common Lisp' },
  matlab: { title: 'MATLAB' },
  eiffel: { title: 'Eiffel' },
  erlang: { title: 'Erlang' },
  perl: { title: 'Perl' },
  tcl: { title: 'Tcl' },
  bash: { title: 'Bash' },
}
