export default {
    'index': { title: '导读' },
    'apple': { title: 'Apple' },
    'microsoft': { title: 'Microsoft' },
    'google': { title: 'Alphabet' },
    'amazon': { title: 'Amazon' },
    'meta-platform': { title: 'Meta' },
    'x': { title: 'X' },
    'nvidia': { title: 'NVIDIA' },
    'tesla': { title: 'Tesla' },
    'netflix': { title: 'Netflix' },
    'broadcom': { title: 'Broadcom' },
    'oracle': { title: 'Oracle' },
    'salesforce': { title: 'Salesforce' },
    'adobe': { title: 'Adobe' },
    'ibm': { title: 'IBM' },
    'intel': { title: 'Intel' },
    'cisco': { title: 'Cisco' },
    'qualcomm': { title: 'Qualcomm' },
}
