export default {
  index: { title: 'Overview' },
  haskell: { title: 'Haskell' },
  python: { title: 'Python' },
  'visual-basic': { title: 'Visual Basic' },
  lua: { title: 'Lua' },
  r: { title: 'R' },
  delphi: { title: 'Delphi' },
  java: { title: 'Java' },
  javascript: { title: 'JavaScript' },
  php: { title: 'PHP' },
  ruby: { title: 'Ruby' },
  ocaml: { title: 'OCaml' },
  'wolfram-language': { title: 'Wolfram Language' },
  'pl-sql': { title: 'PL/SQL' },
  't-sql': { title: 'T-SQL' },
}
