export default {
    overview: { title: 'CNN & Backbone' },
    cnn: { title: 'CNN Architecture' },
    resnet: { title: 'ResNet' },
    batchnorm: { title: 'Batch Normalization' },
    optimizer: { title: 'SGD & Adam & AdamW' },
    scheduler: { title: 'Learning Rate Schedulers' },
    backprop: { title: 'Backpropagation' },
    rcnn: { title: 'R-CNN Family' },
    yolo: { title: 'YOLO' },
    detr: { title: 'DETR' },
    fcn: { title: 'FCN & SAM' },
    gpt: { title: 'GPT Series' },
    claude: { title: 'Claude Series' },
    llama: { title: 'LLaMA Series' },
    gemini: { title: 'Gemini Series' },
    qwen: { title: 'Qwen Series' },
    deepseek: { title: 'DeepSeek Series' },
}
