export default {
  index: { title: 'Overview' },
  'c-sharp': { title: 'C#' },
  actionscript: { title: 'ActionScript' },
  d: { title: 'D' },
  processing: { title: 'Processing' },
  scratch: { title: 'Scratch' },
  scala: { title: 'Scala' },
  groovy: { title: 'Groovy' },
  'f-sharp': { title: 'F#' },
  haxe: { title: 'Haxe' },
  powershell: { title: 'PowerShell' },
  clojure: { title: 'Clojure' },
  nim: { title: 'Nim' },
  go: { title: 'Go' },
  coffeescript: { title: 'CoffeeScript' },
  rust: { title: 'Rust' },
}