export default {
    overview: { title: 'RL Fundamentals' },
    mdp: { title: 'MDP & Bellman Equation' },
    qlearning: { title: 'Q-Learning & SARSA' },
    dqn: { title: 'DQN & Variants' },
    policy: { title: 'Policy Gradient & REINFORCE' },
    actor: { title: 'Actor-Critic & A2C/A3C' },
    trpo: { title: 'TRPO' },
   ppo: { title: 'PPO' },
    sac: { title: 'SAC Soft Actor Critic' },
    dyna: { title: 'Dyna & MBPO' },
    world: { title: 'World Models' },
    muzero: { title: 'MuZero' },
    offline: { title: 'Offline RL' },
    cql: { title: 'CQL & IQL' },
    dt: { title: 'Decision Transformer' },
    marl: { title: 'Multi-Agent RL' },
    ctde: { title: 'CTDE & MAPPO/QMIX' },
}