export default {
  index: { title: 'Overview' },
  algol: { title: 'ALGOL' },
  'cobol-61': { title: 'COBOL 61' },
  snobol: { title: 'SNOBOL' },
  'pl-i': { title: 'PL/I' },
  rpg: { title: 'RPG' },
  basic: { title: 'BASIC' },
  apl: { title: 'APL' },
  simula: { title: 'Simula' },
  bcpl: { title: 'BCPL' },
  logo: { title: 'Logo' },
  forth: { title: 'Forth' },
  b: { title: 'B' },
}
