export default {
    index: {
        title: '简介',
        type: 'page',
        display: 'hidden',
        theme: { layout: 'full', toc: false, timestamp: false },
    },
    '---sep-time': { type: 'separator', title: '时间线与语言' },
    'ai-timeline': { title: 'AI 时间线', type: 'page' },
    timeline: { title: '编程语言', type: 'page' },
    '---sep-ai': { type: 'separator', title: '模型 · 软件 · 数据' },
    ais: { title: 'AI 模型', type: 'page' },
    software: { title: '软件层', type: 'page' },
    datasets: { title: 'AI 数据集', type: 'page' },
    '---sep-hw': { type: 'separator', title: '智能硬件与 AGI' },
    hardware: { title: '智能硬件', type: 'page' },
    agi: { title: 'AGI', type: 'page' },
    '---sep-more': { type: 'separator', title: '产业与参考' },
    companies: { title: '科技巨头', type: 'page' },
    appendix: { title: '附录', type: 'page' },
}
