export default {
    overview: { title: 'Vision Transformers' },
    vit: { title: 'ViT Vision Transformer' },
    dit: { title: 'DeiT Data-efficient Image Transformer' },
    swin: { title: 'Swin Transformer' },
    clip: { title: 'CLIP' },
    siglip: { title: 'SigLIP' },
    dino: { title: 'DINO Self-distillation' },
    mae: { title: 'MAE Masked Autoencoder' },
    vlm: { title: 'VLM Vision Language Models' },
    diffusion: {
        title: 'Diffusion Models',
        theme: { collapsed: false },
    },
    score: { title: 'Score Matching & SDE' },
    ddim: { title: 'DDIM' },
    cfg: { title: 'Classifier-Free Guidance' },
    consistency: { title: 'Consistency Models' },
    flow: { title: 'Flow Matching' },
    rectified: { title: 'Rectified Flow' },
    sd3: { title: 'SD3 & FLUX' },
    '3d': { title: '3D Representations', theme: { collapsed: false } },
    nerf: { title: 'NeRF Neural Radiance Fields' },
    ngp: { title: 'Instant-NGP' },
    gaussian: { title: '3D Gaussian Splatting' },
    different: { title: 'Differentiable Rendering' },
}
